config/routes.rb
Consumr::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'users#show'

  resources :media
  resources :users, only: [:index, :show]
  resources :recommendations, only: [:create, :new, :index, :destroy]
  resource :friendships, only: [:index] do
    member do
      post :friend_request
      post :accept
      post :reject
      get :my_friends
    end
  end
  resource :search, only: [:index] do
    member do
      post :search
    end
  end

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  default_scope { order("created_at DESC") }

  validates :body, presence: true
  validates :user_id, presence: true
  validates :creator_id, presence: true
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user = User.find(params[:u_id])
    @recommendation = Recommendation.new
    respond_to do |format|
        format.html
        format.js { render 'recommendations/new' }
      end
  end

  def create
    @user = User.find(params[:user])
    @recommendation = @user.recommendations.build(recommendation_params_create)
    if @recommendation.save
      flash[:notice] = "Your recommendation has been created!"
      redirect_to @user
    else
      flash[:notice] = "There was a problem creating your recommendation."
      redirect_to @user
    end
  end

  def index
    @recommendations = current_user.recommendations
    @recommendations = @recommendations.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    if @recommendation.destroy
      flash[:notice] = "Your recommendation was successfully deleted"
      redirect_to recommendations_path
    else
      flash[:notice] = "There was an error removing your recommendation"
      redirect_to recommendations_path
    end
  end

  private

  def recommendation_params_create
    params.require(:recommendation).permit(:creator_id, :body)
  end
end

app/views/recommendations/_new.html.erb
<%= simple_form_for @recommendation, :url => recommendations_path(user: @user) do |f| %>
  <%= f.input :body %>
  <%= f.hidden_field :creator_id, :value => current_user.id %>
  <%= f.submit "Recommend", :class => "button small radius success" %>
<% end %>

app/views/recommendations/index.html.erb
<div class="row">
  <div class="small-12 large-6 large-offset-3 columns">
    <h2 class="rec_header">All Recommendations</h2>
    <div class="all_recommendations">
      <% if @recommendations %>
        <ul class="recent_recommendations">
          <% @recommendations.each do |r| %>
            <li>
              <%= button_to "X", recommendation_path(r.id), method: :delete, :class => 'circle' %>
              <span><%= r.body %> </span>
              <span>-(<a href="/users/<%= r.creator_id %>"><%= User.find(r.creator_id).full_name %></a>)</span>
              <br /><br />
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="clear"></div>
    <%= will_paginate @recommendations %>
  </div>
</div>

app/views/recommendations/new.js.erb
$('#recommendations').empty();
$('#recommendations').html('<%= j render 'recommendations/new' %>');
$('#recommendation_body').focus();