config/routes.rb
Consumr::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'users#show'

  resources :media
  resources :users, only: [:index, :show]
  resources :recommendations, only: [:create, :new, :index, :destroy]
  resource :friendships, only: [:index] do
    member do
      post :friend_request
      post :accept
      post :reject
      get :my_friends
    end
  end
  resource :search, only: [:index] do
    member do
      post :search
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :media, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, source: :friend
  has_many :recommendations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                          )
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
    @current_media = @user.media.current_media if @user
    @wish_list = @user.media.wish_list if @user
    @finished_media = @user.media.finished if @user
    @recommendations = @user.recommendations if @user
    if current_user != @user
      friendship = Friendship.find_by(user: current_user, friend: @user)
      @friendship = friendship if friendship && friendship.status = "accepted"
    end
  end
end

app/views/users/index.html.erb
<div class="row">
  <div class="small-12 large-8 large-offset-2 all_users_container">
    <h1>All users</h1>
    <ul class="all_users_list">
      <%= render 'shared/user_profile_info', users: @users %>
    </ul>
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<% unless user_signed_in? %>
  <%= render 'shared/home' %>
<% else %>
  <div class="row">
    <div class="large-6 small-12 columns">
      <div class="profile_container">
        <div class="user_info">
          <%= image_tag avatar_url(@user) %>
        </div>
        <div class="username">
          <%= @user.full_name %>
        </div>
        <% if @user == current_user %>
          <%= button_to 'Edit Profile', edit_user_registration_path(current_user), :method => :get, class: 'edit button tiny radius' %>
        <% else %>
          <div class="friendship_status">
            <% if Friendship.are_friends(current_user, User.find_by(id: params[:id])) %>
              <%= current_user.friendships.where(friend_id: params[:id]).first.status.capitalize %> Friends
            <% else %>
              <%= link_to "Request Friendship", friend_request_friendships_path(friend_id: params[:id]), method: :post %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="user_favorites">
        <ul class="favorites">
          <li><b class="user_favorites_title">Favorite Movies:</b> <span><%= @user.fav_movies %></span></li>
            <li><b class="user_favorites_title">Favorite TV Shows:</b> <span><%= @user.fav_tv %></span></li>
            <li><b class="user_favorites_title">Favorite Books:</b> <span><%= @user.fav_books %></span></li>
        </ul>
      </div>
      <div class="clear"></div>
      <div class="recommendations">
        <% if @recommendations %>
          <div class="row recommendation_header">
            <div class="small-5 columns">
              <h2 class="user_subheader">Recommendations</h2>
            </div>
            <div class="small-7 columns">
                <% if @friendship %>
                  <%= form_tag(new_recommendation_path(u_id: @user.id), method: :get, remote: true) do %>
                    <%= submit_tag "Add", class: 'new_recommendation button tiny radius success' %>
                  <% end %>
                <% elsif @user == current_user %>
                  <a href='/recommendations' class="button tiny radius new_recommendation">All</a>
                <% end %>
            </div>
          </div>
          <ul class="recent_recommendations">
            <% @recommendations.each_with_index do |r, i| %>
              <% break if i == 3 %>
              <li>
                <span><%= r.body %> </span>
                <span>-(<a href="/users/<%= r.creator_id %>"><%= User.find(r.creator_id).full_name %></a>)</span>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div id="recommendations" class="recommendations">
      </div>
    </div>
    <div class="large-6 small-12 columns">
      <div class="current_media">
        <div class="wrapper">
          <%= render 'shared/slideshow_header', user: @user, status: "Current" %>
          <% if @current_media.any? %>
            <div class="current_media_all">
              <%= render 'shared/slideshow', media: @current_media, status: "current" %>
            </div>
          <% end %>
        </div>
        <div class="wrapper">
          <%= render 'shared/slideshow_header', user: @user, status: "Wish List" %>
          <% if @wish_list.any? %>
            <div class="wish_list_all">
              <%= render 'shared/slideshow', media: @wish_list, status: "wish" %>
            </div>
          <% end %>
        </div>
        <div class="wrapper">
          <%= render 'shared/slideshow_header', user: @user, status: "Finished" %>
          <% if @finished_media.any? %>
            <div class="finished_all">
              <%= render 'shared/slideshow', media: @finished_media, status: "finished" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>