config/routes.rb
Consumr::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'users#show'

  resources :media
  resources :users, only: [:index, :show]
  resources :recommendations, only: [:create, :new, :index, :destroy]
  resource :friendships, only: [:index] do
    member do
      post :friend_request
      post :accept
      post :reject
      get :my_friends
    end
  end
  resource :search, only: [:index] do
    member do
      post :search
    end
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"

  scope :pending_friends, -> { where status: "pending" }
  scope :requested_friends, -> { where status: "requested" }
  scope :accepted_friends, -> { where status: "accepted" }

  validates :user_id, presence: true
  validates :friend_id, presence: true

  def self.are_friends(user, friend)
    return false if user == friend
    unless Friendship.find_by(user: user, friend: friend).nil? || Friendship.find_by(user: friend, friend: user).nil?
      return true
    end
    false
  end

  def self.request(user, friend)
    return false if Friendship.are_friends(user,friend) || user == friend
    friend1 = Friendship.new(user: user, friend: friend, status: "pending")
    friend2 = Friendship.new(user: friend, friend: user, status: "requested")
    transaction do
      friend1.save
      friend2.save
    end
    true
  end

  def self.accept(user, friend)
    friend1 = Friendship.find_by(user: user, friend: friend)
    friend2 = Friendship.find_by(user: friend, friend: user)
    return false if friend1.nil? || friend2.nil?
    transaction do
      friend1.update(status: "accepted")
      friend2.update(status: "accepted")
    end
    true
  end

  def self.reject(user, friend)
    friend1 = Friendship.find_by(user: user, friend: friend)
    friend2 = Friendship.find_by(user: friend, friend: user)
    return false if friend1.nil? || friend2.nil?
    transaction do
      friend1.destroy
      friend2.destroy
      true
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate_user!

  def friend_request
    @user = current_user
    @friend = User.find(params[:friend_id])
    unless @friend.nil?
      if Friendship.request(@user, @friend)
        flash[:notice] = "Friendship requested with #{@friend.full_name}."
      else
        flash[:notice] = "Friendship unable to be requested with #{@friend.full_name}."
      end
    end
    redirect_to @friend
  end

  def my_friends
    @pending = []
    @requests = current_user.friendships.requested_friends
    @friends = []
    current_user.friendships.pending_friends.each do |f|
      @pending << User.find(f.friend_id)
    end
    current_user.friendships.accepted_friends.each do |f|
      @friends << User.find(f.friend_id)
    end
    @friends = @friends.paginate(page: params[:page], per_page: 5)
    render "/friendships/my_friends"
  end

  def accept
    @user = current_user
    @friend = User.find_by(id: params[:f_id])
    unless @friend.nil?
      if Friendship.accept(@user, @friend)
        flash[:notice] = "Friendship accepted with #{@friend.full_name}."
      else
        flash[:notice] = "Friendship unable to be accepted with #{@friend.full_name}."
      end
    end
    redirect_to my_friends_friendships_path
  end

  def reject
    @user = current_user
    @friend = User.find_by(id: params[:f_id])
    unless @friend.nil?
      if Friendship.reject(@user, @friend)
        flash[:notice] = "Friendship rejected with #{@friend.full_name}."
      else
        flash[:notice] = "Friendship unable to be rejected with #{@friend.full_name}."
      end
    end
    redirect_to my_friends_friendships_path
  end
end

app/views/friendships/my_friends.html.erb
<div class="row">
  <div class="small-12 large-12 columns">
    <h1 class="my_friends_title">My Friends</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 large-6 columns">
    <div id="friend_requests">
      <h2>Friend Requests</h2>
      <% if @requests.any? %>
        <% @requests.each do |r| %>
          <%= button_to "X", reject_friendships_path(f_id: r.friend_id), method: :post, :class => "circle" %>
          <%= User.find(r.friend_id).full_name %>
          <%= link_to "Accept", accept_friendships_path(f_id: r.friend_id), method: :post %>
        <% end %>
      <% else %>
        No friend requests as of now
      <% end %>
    </div>
    <div id="pending_friends">
      <h2>Pending Friends</h2>
      <% if @pending.any? %>
        <% @pending.each do |p| %>
          <%= p.full_name %>
        <% end %>
      <% else %>
        No pending friends as of now
      <% end %>
    </div>
  </div>
  <div class="small-12 large-6 columns">
    <div id="all_friends">
      <h2>All Friends</h2>
      <ul class="all_friends_list">
        <%= render 'shared/user_profile_info', users: @friends %>
      </ul>
      <%= will_paginate @friends %>
    </div>
  </div>
</div>