config/routes.rb
Consumr::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'users#show'

  resources :media
  resources :users, only: [:index, :show]
  resources :recommendations, only: [:create, :new, :index, :destroy]
  resource :friendships, only: [:index] do
    member do
      post :friend_request
      post :accept
      post :reject
      get :my_friends
    end
  end
  resource :search, only: [:index] do
    member do
      post :search
    end
  end

end

app/views/layouts/_nav.html.erb
<div class="contain-to-grid">
  <nav class='top-bar' data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="/" class="logo">CONSUMR</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"></a></li>
    </ul>
    <section class="top-bar-section">
      <ul class='right'>
        <% if current_user %>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'All Users', users_path %></li>
          <li><%= link_to 'My Media', media_path %></li>
          <li><%= link_to 'My Friends', my_friends_friendships_path %></li>
          <li><%= link_to 'My Account', edit_user_registration_path(current_user) %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'signout' %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path, :class => 'signin' %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CONSUMR" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="http://malsup.github.com/jquery.cycle2.js"></script>
    <script src="http://malsup.github.com/jquery.cycle2.center.js"></script>
    <script src="http://malsup.github.io/min/jquery.cycle2.swipe.min.js"></script>
  </body>
</html>